// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FB_MapHUD","status":true,"description":"","parameters":{}},
{"name":"CVMap","status":true,"description":"","parameters":{}},
{"name":"FB_WindowReform","status":true,"description":"","parameters":{}},
{"name":"FB_BaseWidgets","status":true,"description":"","parameters":{}}
];
