
all: rebour rempli_rec somme_chiffre recherche racine_carre tri_simple sac_a_dos

CC = gcc

rebour: ex1_rebour.c
	$(CC) ex1_rebour.c -o ex1

rempli_rec: ex2_rempli_rec.c
	$(CC) ex2_rempli_rec.c -o ex2

somme_chiffre: ex3_somme_chiffre.c
	$(CC) ex3_somme_chiffre.c -o ex3

recherche: ex4_recherche.c
	$(CC) ex4_recherche.c -o ex4

racine_carre: ex5_racine_carre.c
	$(CC) ex5_racine_carre.c -o ex5

tri_simple: ex6_tri_simple.c
	$(CC) ex6_tri_simple.c -o ex6

sac_a_dos: ex7_sac_a_dos.c
	$(CC) ex7_sac_a_dos.c -o ex7
