
# simple make file to compile language C
FLAGS = -Wall -Wextra -g
PROGS = exo1 exo2

all: $(PROGS)


exo1: exo1.c
	gcc $(FLAGS) exo1.c -o exo1

exo2: exo2.c
	gcc $(FLAGS) exo2.c -o exo2

clean:
	rm -r $(PROGS)


